import jsQR from "jsqr";

const SCAN_TESTS = Object.freeze([
  { name: "Full detail", size: 640, blur: 0 },
  { name: "Typical phone view", size: 320, blur: 0 },
  { name: "Small or compressed", size: 180, blur: 0.35 },
]);

/**
 * Loads an in-memory QR image without sending it to a server.
 *
 * @param {Blob} imageBlob - QR image data generated in the browser.
 * @returns {Promise<HTMLImageElement>} A decoded browser image.
 */
function loadBlobImage(imageBlob) {
  return new Promise((resolve, reject) => {
    const imageUrl = URL.createObjectURL(imageBlob);
    const image = new Image();

    image.onload = () => {
      URL.revokeObjectURL(imageUrl);
      resolve(image);
    };
    image.onerror = () => {
      URL.revokeObjectURL(imageUrl);
      reject(new Error("The generated QR image could not be loaded."));
    };
    image.src = imageUrl;
  });
}

/**
 * Runs one local decode attempt at a representative display size.
 *
 * @param {HTMLImageElement} image - The generated QR image.
 * @param {{ size: number, blur: number }} scanTest - Test rendering settings.
 * @returns {string} The decoded payload, or an empty string when decoding fails.
 */
function decodeAtSize(image, scanTest) {
  const canvas = document.createElement("canvas");
  const context = canvas.getContext("2d", { willReadFrequently: true });

  if (!context) {
    throw new Error("This browser cannot create the scan-check canvas.");
  }

  canvas.width = scanTest.size;
  canvas.height = scanTest.size;
  context.imageSmoothingEnabled = true;
  context.imageSmoothingQuality = "high";
  context.filter = scanTest.blur ? `blur(${scanTest.blur}px)` : "none";
  context.drawImage(image, 0, 0, scanTest.size, scanTest.size);

  const imageData = context.getImageData(0, 0, scanTest.size, scanTest.size);
  const decodedQrCode = jsQR(
    imageData.data,
    imageData.width,
    imageData.height,
    { inversionAttempts: "attemptBoth" },
  );

  return decodedQrCode?.data ?? "";
}

/**
 * Assigns a plain-language result to a group of local decode attempts.
 *
 * @param {number} passedChecks - Number of successful matching decodes.
 * @param {number} totalChecks - Total decode attempts.
 * @returns {"failed" | "caution" | "passed" | "strong"} Scan result.
 */
export function getScanResultStatus(passedChecks, totalChecks) {
  if (passedChecks === 0) {
    return "failed";
  }

  if (passedChecks === 1) {
    return "caution";
  }

  if (passedChecks === totalChecks) {
    return "strong";
  }

  return "passed";
}

/**
 * Decodes a generated QR under multiple local, simulated viewing conditions.
 *
 * @param {Blob} qrImageBlob - A PNG generated by qr-code-styling.
 * @param {string} expectedPayload - The value the QR should contain.
 * @returns {Promise<object>} Detailed scanability result.
 */
export async function evaluateQrCodeScanability(
  qrImageBlob,
  expectedPayload,
) {
  const image = await loadBlobImage(qrImageBlob);
  const checks = SCAN_TESTS.map((scanTest) => {
    const decodedPayload = decodeAtSize(image, scanTest);

    return {
      name: scanTest.name,
      passed: decodedPayload === expectedPayload,
    };
  });
  const passedChecks = checks.filter((check) => check.passed).length;

  return {
    checks,
    passedChecks,
    totalChecks: checks.length,
    status: getScanResultStatus(passedChecks, checks.length),
  };
}
